name = "SaddlePaths"
uuid = "871ff458-9e65-4f8e-a9a5-6c0d437cc13a"
authors = ["Koren"]
version = "0.1.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
